// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoExamenU2POO.Database;

#nullable disable

namespace ProyectoExamenU2POO.Migrations
{
    [DbContext(typeof(ProyectoExamenContext))]
    [Migration("20240727001930_createClientTable")]
    partial class createClientTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProyectoExamenU2POO.Database.Entities.ClienteEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("FechaDesembolso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fecha_desembolso");

                    b.Property<string>("FechaPrimerPago")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fecha_primer_pago");

                    b.Property<int>("MontoComision")
                        .HasColumnType("int")
                        .HasColumnName("monto_comision");

                    b.Property<int>("MontoPrestamo")
                        .HasColumnType("int")
                        .HasColumnName("monto_prestano");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nombre");

                    b.Property<int>("Plazo")
                        .HasColumnType("int")
                        .HasColumnName("plazo");

                    b.Property<int>("TasaInteres")
                        .HasColumnType("int")
                        .HasColumnName("tasa_interes");

                    b.HasKey("Id");

                    b.ToTable("clientes", "dbo");
                });
#pragma warning restore 612, 618
        }
    }
}
