// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoExamenU2POO.Database;

#nullable disable

namespace ProyectoExamenU2POO.Migrations
{
    [DbContext(typeof(ProyectoExamenContext))]
    [Migration("20240727130558_DBinit")]
    partial class DBinit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProyectoExamenU2POO.Database.Entities.PagoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<double>("CuotaConSVSD")
                        .HasColumnType("float")
                        .HasColumnName("cuota_con_svsd");

                    b.Property<double>("CuotaSinSvsd")
                        .HasColumnType("float")
                        .HasColumnName("cuota_sin_svsd");

                    b.Property<DateOnly>("FechaDePago")
                        .HasColumnType("date")
                        .HasColumnName("fecha_pago");

                    b.Property<double>("Interes")
                        .HasColumnType("float")
                        .HasColumnName("interes");

                    b.Property<int>("NumeroCuota")
                        .HasColumnType("int")
                        .HasColumnName("num_cuota");

                    b.Property<double>("Principal")
                        .HasColumnType("float")
                        .HasColumnName("principal");

                    b.Property<double>("SaldoPrincipal")
                        .HasColumnType("float")
                        .HasColumnName("saldo_principal");

                    b.HasKey("Id");

                    b.ToTable("pago", "dbo");
                });

            modelBuilder.Entity("ProyectoExamenU2POO.Database.Entities.PrestamoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateOnly>("FechaDesembolso")
                        .HasColumnType("date")
                        .HasColumnName("fecha_desembolso");

                    b.Property<DateOnly>("FechaPrimerPago")
                        .HasColumnType("date")
                        .HasColumnName("fecha_primer_pago");

                    b.Property<int>("MontoComision")
                        .HasColumnType("int")
                        .HasColumnName("monto_comision");

                    b.Property<int>("MontoPrestamo")
                        .HasColumnType("int")
                        .HasColumnName("monto_prestamo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nombre");

                    b.Property<int>("Plazo")
                        .HasColumnType("int")
                        .HasColumnName("plazo");

                    b.Property<int>("TasaInteres")
                        .HasColumnType("int")
                        .HasColumnName("tasa_interes");

                    b.HasKey("Id");

                    b.ToTable("prestamo", "dbo");
                });

            modelBuilder.Entity("ProyectoExamenU2POO.Database.Entities.PrestamoPagoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("PagoId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("pago_id");

                    b.Property<Guid>("PrestamoId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("prestamo_id");

                    b.HasKey("Id");

                    b.HasIndex("PagoId");

                    b.HasIndex("PrestamoId");

                    b.ToTable("prestamo_pago", "dbo");
                });

            modelBuilder.Entity("ProyectoExamenU2POO.Database.Entities.PrestamoPagoEntity", b =>
                {
                    b.HasOne("ProyectoExamenU2POO.Database.Entities.PagoEntity", "Pago")
                        .WithMany()
                        .HasForeignKey("PagoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyectoExamenU2POO.Database.Entities.PrestamoEntity", "Prestamo")
                        .WithMany("Pagos")
                        .HasForeignKey("PrestamoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pago");

                    b.Navigation("Prestamo");
                });

            modelBuilder.Entity("ProyectoExamenU2POO.Database.Entities.PrestamoEntity", b =>
                {
                    b.Navigation("Pagos");
                });
#pragma warning restore 612, 618
        }
    }
}
